export const environment = {
    production: false,
    tinymceKey: "dwoldyojyg230749ofwakj5oobpvav9spnghkx2293xbjlx5",
    getTripCategoriesUrl: "https://localhost:7013/api/categories",
    getTripCategoryAdminUrl:"https://localhost:7013/api/admin/categories/GetCategoryByName",
    getTripCategoryUrl:"https://localhost:7013/api/categories",
    tripAdminUrl:"https://localhost:7013/api/admin/trips/",
    getTransportTypesUrl: "https://localhost:7013/api/transporttypes",
    loginUrl: 'https://localhost:7013/api/account/login',
    refreshTokenUrl: "https://localhost:7013/api/account/refresh",
    getHeaderDataUrl: "https://localhost:7013/api/trips/header",
    getTripUrl: "https://localhost:7013/api/trips",
    getHighlightedTripsUrl: "https://localhost:7013/api/trips/highlighted",
    getSearchUrl: "https://localhost:7013/api/categories/search",
    getSearchAdminUrl: "https://localhost:7013/api/admin/categories/search",
    getSubPageUrl:"https://localhost:7013/api/subpages",
    getSubPagesUrl:"https://localhost:7013/api/subpages",
    subpageAdminUrl: "https://localhost:7013/api/admin/subpages/",
    categoryAdminUrl: "https://localhost:7013/api/admin/categories/",
    contactAdminUrl: "https://localhost:7013/api/admin/contacts",
    deleteSubPageAdminUrl: "https://localhost:7013/api/admin/subpages/",
    deleteCategoryAdminUrl: "https://localhost:7013/api/admin/categories/",
    deleteTripAdminUrl: "https://localhost:7013/api/admin/trips/",
    textBoxCharactersLimit: 255,
    allowedFileExtensions: ".jpg,.png,.jpeg",
    maxFileSizeBytes: "5242880" //5MB
}